[package]
name = "trivial-kernel"
version = "0.7.0"
authors = ["Ivo C.S. Wingelaar <ivo@codeforge.rs>"]
description = "A Metamath Zero kernel for Trivial"
keywords = ["metamath-zero", "trivial"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
mmb-types = "0.3.0"
